"""Walmart CA line definitions ported from Books_by_Rudra v0 zoho_account_mapping.WALMART_LINE_DEFS."""

from __future__ import annotations

from typing import Any

WALMART_LINE_DEFS: list[dict[str, Any]] = [
    {
        "key": "product_price",
        "label": "Product Price (Line Amount)",
        "csv_column": "Product price",
        "default_setting": "ZOHO_WALMART_SALES_ACCOUNT_ID",
        "default_account_name": "Sales",
        "entry_type": "Debit",
        "mapped_amount_keys": ("line_amount",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "line_shipping",
        "label": "Line Shipping Charge",
        "csv_column": "Line Shipping Charge",
        "default_setting": "ZOHO_WALMART_SHIPPING_COLLECTED_ACCOUNT_ID",
        "default_account_name": "Shipping Collected from Sales",
        "entry_type": "Debit",
        "mapped_amount_keys": ("line_shipping_charge",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "line_fee",
        "label": "Line Fee",
        "csv_column": "Line Fee",
        "default_setting": "ZOHO_WALMART_SHIPPING_COLLECTED_ACCOUNT_ID",
        "default_account_name": "Shipping Collected from Sales",
        "entry_type": "Debit",
        "mapped_amount_keys": ("line_fee",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "line_tax",
        "label": "Line Tax (Canada Sales Tax)",
        "csv_column": "Line Tax",
        "default_setting": "ZOHO_WALMART_SALES_TAX_CA_ACCOUNT_ID",
        "default_account_name": "Sales Tax CA",
        "entry_type": "Debit",
        "mapped_amount_keys": ("line_tax",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "pst_qst_walmart_remittance",
        "label": "PST/QST Remit by Walmart",
        "csv_column": "PST/QST Remit by Walmart",
        "default_setting": "ZOHO_WALMART_SALES_TAX_CA_ACCOUNT_ID",
        "default_account_name": "Sales Tax CA",
        "entry_type": "Debit",
        "mapped_amount_keys": ("pst_qst_walmart",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "gst_hst_walmart_remittance",
        "label": "GST/HST Remit by Walmart",
        "csv_column": "GST/HST Remit by Walmart",
        "default_setting": "ZOHO_WALMART_SALES_TAX_CA_ACCOUNT_ID",
        "default_account_name": "Sales Tax CA",
        "entry_type": "Debit",
        "mapped_amount_keys": ("gst_hst_walmart",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "referral_item",
        "label": "Referral Amount on Item",
        "csv_column": "Referral Amount on Item",
        "default_setting": "ZOHO_WALMART_SELLING_EXP_ACCOUNT_ID",
        "default_account_name": "Walmart Selling Exp (CA)",
        "entry_type": "Credit",
        "mapped_amount_keys": ("referral_amount_on_item",),
        "mapping_document_kind": "journal",
    },
    {
        "key": "referral_shipping",
        "label": "Referral Amount on Shipping",
        "csv_column": "Referral Amount on shipping",
        "default_setting": "ZOHO_WALMART_SELLING_EXP_ACCOUNT_ID",
        "default_account_name": "Walmart Selling Exp (CA)",
        "entry_type": "Credit",
        "mapped_amount_keys": ("referral_amount_on_shipping",),
        "mapping_document_kind": "journal",
    },
    {
        "key": "referral_tax",
        "label": "Referral Tax Amount",
        "csv_column": "Referral Tax Amount",
        "default_setting": "ZOHO_WALMART_REFERRAL_TAX_ACCOUNT_ID",
        "default_account_name": "Referral Tax (Walmart)",
        "entry_type": "Credit",
        "mapped_amount_keys": ("referral_tax_amount",),
        "mapping_document_kind": "journal",
    },
    {
        "key": "wfs_fee",
        "label": "WFS Fee Amount",
        "csv_column": "WFS Fee Amount",
        "default_setting": "ZOHO_WALMART_SELLING_EXP_ACCOUNT_ID",
        "default_account_name": "Walmart Selling Exp (CA)",
        "entry_type": "Credit",
        "mapped_amount_keys": ("wfs_fee",),
        "mapping_document_kind": "journal",
    },
    {
        "key": "wfs_pst_qst",
        "label": "WFS PST/QST",
        "csv_column": "WFS PST/QST",
        "default_setting": "ZOHO_WALMART_SALES_TAX_CA_ACCOUNT_ID",
        "default_account_name": "Sales Tax CA",
        "entry_type": "Credit",
        "mapped_amount_keys": ("wfs_pst_qst",),
        "mapping_document_kind": "invoice",
    },
    {
        "key": "wfs_gst_hst",
        "label": "WFS GST/HST",
        "csv_column": "WFS GST/HST",
        "default_setting": "ZOHO_WALMART_SALES_TAX_CA_ACCOUNT_ID",
        "default_account_name": "Sales Tax CA",
        "entry_type": "Credit",
        "mapped_amount_keys": ("wfs_gst_hst",),
        "mapping_document_kind": "invoice",
    },
]
